version = 61
name = "SpaceX Plotter (POC)"
description = "Proof of concept application demonstrating interfacing of two HTTP APIs"
authors = ["christopher.peters+fastlyce@cbsinteractive.com"]
language = "assemblyscript"
service_id = "1SMGMYuaK45wCXlU0v5R5u"
